export const getMoves = state => state.simonSays.moves
export const getPlayers = state => state.simonSays.players
export const getPads = state => state.simonSays.pads
export const selectPerformingPlayer = state => state.simonSays.players[0]
export const isGameOver = state => state.simonSays.game.isGameOver
export const getCurrentRound = state => state.simonSays.game.round
export const hasFoundMatch = state => state.simonSays.game.hasFoundMatch
export const isDisplayingMoves = state => state.simonSays.game.isDisplayingMoves
export const getTimer = state => state.simonSays.game.timer
